# Generated by Django 2.1.4 on 2019-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190101_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.CharField(default='A Combat story', max_length=300),
            preserve_default=False,
        ),
    ]
